### ISSUE TITLE
[Request] :recipe support

### ISSUE THREAD

**Issue by vtrf** [nix-community/nix-doom-emacs#177]
Would love if recipe support was possible. Without its almost impossible to use nix-doom-emacs.

Reference: https://github.com/vlaci/nix-straight.el/issues/7

**Comment by ckiee** [comment]
(Transferred because really `nix-straight.el`'s issues should go here. Also disabled issues over there)

Check out https://github.com/vlaci/nix-straight.el/issues/1: we currently only obtain the list of needed packages and use whatever versions emacs-overlay has. This is the way it was implemented pre-vlaci-fork and my last attempt at fixing it was very frustrating and I ran out of patience.

A workaround would be to use [`emacsPackagesOverlay`](https://github.com/nix-community/nix-doom-emacs/blob/96209801150e898e080d75e571403a48cad05b21/default.nix#L28-L39).

**Comment by ratsclub** [comment]
Solved like this:

```nix
    emacsPackagesOverlay = self: super: {
      denote = self.trivialBuild {
        pname = "denote";
        ename = "denote";
        version = "0.1.0";
        src = pkgs.fetchFromSourcehut {
          repo = "denote";
          owner = "~protesilaos";
          rev = "0.1.0";
          sha256 = "sha256-csY9dxUpTw6hWwL+JJnNOsbLNlToIfh/gsdxS1uEQtg";
        };
      };
    };
```

**Comment by sepiabrown** [comment]
> Solved like this:
> 
> ```nix
>     emacsPackagesOverlay = self: super: {
>       denote = self.trivialBuild {
>         pname = "denote";
>         ename = "denote";
>         version = "0.1.0";
>         src = pkgs.fetchFromSourcehut {
>           repo = "denote";
>           owner = "~protesilaos";
>           rev = "0.1.0";
>           sha256 = "sha256-csY9dxUpTw6hWwL+JJnNOsbLNlToIfh/gsdxS1uEQtg";
>         };
>       };
>     };
> ```

Thank you!
