### ISSUE TITLE
Merge develop to master?

### ISSUE THREAD

**Issue by ulysses4ever** [nix-community/nix-doom-emacs#3]
AFAIR there were some useful bits in `develop`.

**Comment by cole-h** [comment]
FWIW, here's the difference: https://github.com/nix-community/nix-doom-emacs/compare/master...nix-community:develop

Mostly flake.lock related changes, but the most recent commits look like they might be nice.

**Comment by ckiee** [comment]
- https://github.com/nix-community/nix-doom-emacs/commit/656a3aea172d6fb99a1d6e5c45667121855e5996: cherry-picked now, thanks!
- https://github.com/nix-community/nix-doom-emacs/commit/03922f80e502517118b23bb2d0612a8f9565e9ca: boring
- https://github.com/nix-community/nix-doom-emacs/commit/1e91c408bed930ede94cdd3728372d38d7794523: duplicated in https://github.com/nix-community/nix-doom-emacs/commit/9bf739f4a7c9e5813c6bc11af9ca3752486bb1ff, I should probably search for existing solutions before writing my own code more
- https://github.com/nix-community/nix-doom-emacs/commit/dd72c734c7dea3f6c13bd7c71f7656b0e2174d1e: there's no point in exposing this since IIRC stuff breaks on newer straight.el versions.

[Also, we forgot to watch this repository so pure curiosity got me to find this issue, fixed now]
