### ISSUE TITLE
error: getting status of '/nix/store/bbi0bn9i9dslcrc1nasckhbkb8gqd66m-source/doom/doom.d': No such file or directory

### ISSUE THREAD

**Issue by davidhaley** [nix-community/nix-doom-emacs#427]
Hello,

I am receiving this error when I run `nix develop` from my workspace folder. I'm new to nix, so it's likely something that I'm doing wrong.

In a workspace folder:
```
doom/
├── flake.lock
└── flake.nix

0 directories, 2 files
```

In home (excluding extra files/folders):
```
.doom.d
├── config.el
├── custom.el
├── init.el
├── packages.el
```

trace: https://pastebin.com/kt4yGnz2

flake.nix: https://pastebin.com/3FqJU2XP

flake.lock: https://pastebin.com/caeMvXtB

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.27, NixOS, 22.11 (Raccoon), 22.11.4091.a08e061a4ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager, nixos-22.11"`
 - channels(dh): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
 
 `GNU Emacs 28.2`

**Comment by schradert** [comment]
Your `doom.d` directory should be in the same location as your flake files; that's why it errors with `.../doom/doom.d: No such file or directory`. My understanding is you put them in `˜`, which would not be accessible by your flake project if that's different from your project root location. Pure nix evaluations (like using flakes without `--impure`) generally require all files to be in the project's version control system.

**Comment by davidhaley** [comment]
Thanks @schradert
